# Generated by Django 6.0.5 on 2026-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auto_dispatch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_digital',
        ),
        migrations.AddField(
            model_name='product',
            name='contact_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Good'), ('DIGITAL', 'Digital Asset'), ('ACCOUNT', 'Access Credentials'), ('SERVICE', 'Professional Service')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
