# Generated by Django 6.0.5 on 2026-05-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_auto_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='Step-by-step login or activation guide'),
        ),
    ]
