# Generated by Django 6.0.5 on 2026-05-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xmr_multisig_pubkey',
            field=models.CharField(blank=True, help_text="The Vendor's Monero Public Spend Key for Multisig", max_length=255, null=True),
        ),
    ]
