# Generated by Django 6.0.5 on 2026-05-19 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_xmr_multisig_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Moderator feedback or rejection reasons visible to the vendor.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_proof',
            field=models.TextField(blank=True, help_text='PGP signed statement of intent, past marketplace rep links, or identity proof.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
