# Generated by Django 6.0.5 on 2026-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_verification_notes_user_verification_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active / Online'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
