# Generated by Django 6.0.5 on 2026-05-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mod_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active / Online'), ('REJECTED', 'Rejected'), ('FIX_REQUIRED', 'Fix Required'), ('SUSPENDED', 'Permanently Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
