# Generated by Django 6.0.5 on 2026-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_mod_notes_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_status',
            field=models.CharField(choices=[('NONE', 'Active'), ('PAUSED', 'Temporarily Paused'), ('PERMANENT', 'Permanently Banned')], db_index=True, default='NONE', max_length=20),
        ),
    ]
